onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/clk_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/rst_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/hart_id_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/irq_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/flush_i_valid_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/flush_i_ready_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/inst_addr_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/inst_cacheable_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/inst_data_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/inst_valid_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/inst_ready_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_qreq_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_qrsp_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_qvalid_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_qready_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_prsp_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_pvalid_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_pready_o}
add wave -noupdate -group i_snitch -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_finished_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_str_finished_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/data_req_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/data_rsp_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ptw_valid_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ptw_ready_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ptw_va_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ptw_ppn_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ptw_pte_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ptw_is_4mega_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/fpu_rnd_mode_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/fpu_fmt_mode_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/fpu_status_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/core_events_o}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/illegal_inst}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/illegal_csr}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/interrupt}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ecall}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ebreak}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/zero_lsb}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/meip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/mtip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/msip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/mcip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/seip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/stip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ssip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/scip}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/interrupts_enabled}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/any_interrupt_pending}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/pc_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/pc_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/wfi_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/wfi_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/consec_pc}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/iimm}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/uimm}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/jimm}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/bimm}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/simm}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/opa}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/opb}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/adder_result}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/alu_result}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/rd}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/rs1}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/rs2}
add wave -noupdate -group i_snitch -color Orchid {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/stall}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/valid_instr}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_stall}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/gpr_raddr}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/gpr_rdata}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/gpr_waddr}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/gpr_wdata}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/gpr_we}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/sb_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/sb_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/is_load}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/is_store}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/is_signed}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/is_fp_load}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/is_fp_store}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ls_misaligned}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ld_addr_misaligned}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/st_addr_misaligned}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/inst_addr_misaligned}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/itlb_valid}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/itlb_ready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/itlb_va}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/itlb_page_fault}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/itlb_pa}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dtlb_valid}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dtlb_ready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dtlb_va}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dtlb_page_fault}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dtlb_pa}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/trans_ready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/trans_active}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/itlb_trans_valid}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dtlb_trans_valid}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/trans_active_exp}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/tlb_flush}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ls_size}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ls_amo}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ld_result}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_qready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_qvalid}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_tlb_qready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_tlb_qvalid}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_pvalid}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_pready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_empty}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ls_paddr}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_rd}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/retire_load}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/retire_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/retire_acc}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_stall}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/exception}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/alu_op}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/opa_select}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/opb_select}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/write_rd}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/uses_rd}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/next_pc}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/rd_select}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/rd_bypass}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/is_branch}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/csr_rvalue}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/csr_en}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/scratch_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/scratch_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/epc_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/epc_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/tvec_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/tvec_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/cause_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/cause_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/cause_irq_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/cause_irq_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/spp_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/spp_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/mpp_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/mpp_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ie_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ie_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/pie_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/pie_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/eie_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/eie_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/tie_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/tie_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/sie_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/sie_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/cie_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/cie_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/seip_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/seip_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/stip_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/stip_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ssip_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/ssip_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/scip_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/scip_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/priv_lvl_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/priv_lvl_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/satp_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/satp_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dcsr_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dcsr_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dpc_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dpc_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dscratch_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dscratch_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/debug_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/debug_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/fcsr_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/fcsr_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/read_fcsr}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/cycle_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/instret_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/retired_instr_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/retired_load_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/retired_i_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/retired_acc_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/mseg_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/mseg_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_register_rd}
add wave -noupdate -group i_snitch -color Orchid {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_stall}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_store}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/operands_ready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/dst_ready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/opa_ready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/opb_ready}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/npc}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_opa}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_opa_reversed}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_right_result}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_left_result}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_opa_ext}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_right_result_ext}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_left}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/shift_arithmetic}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/alu_opa}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/alu_opb}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/lsu_qdata}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_cnt_q}
add wave -noupdate -group i_snitch -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_finished_i}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_cnt_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_str_cnt_q}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/acc_mem_str_cnt_d}
add wave -noupdate -group i_snitch {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_snitch/alu_writeback}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/clk_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/rst_ni}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/testmode_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/hart_id_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_valid_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_ready_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_req_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_rsp_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/rsp_valid_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/rsp_ready_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/rsp_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_req_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_req_valid_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_req_ready_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_rsp_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_rsp_valid_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_finished_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_str_finished_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/fp_lsu_mem_req_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/fp_lsu_mem_rsp_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/fpu_rnd_mode_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/fpu_fmt_mode_i}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/fpu_status_o}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_req}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_req_valid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vfu_req_ready}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vfu_rsp_ready}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vfu_rsp_valid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vfu_rsp}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vlsu_req_ready}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vlsu_rsp_valid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vlsu_rsp}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vsldu_req_ready}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vsldu_rsp_valid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vsldu_rsp}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_req}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_valid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_ready}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/issue_rsp}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/resp}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/resp_valid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/resp_ready}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/fp_lsu_mem_finished}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/fp_lsu_mem_str_finished}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_finished}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/spatz_mem_str_finished}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_waddr}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_wdata}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_we}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_wbe}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_wvalid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_raddr}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_re}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_rdata}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/vrf_rvalid}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/sb_re}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/sb_we}
add wave -noupdate -group i_spatz {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/sb_id}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/clk_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/rst_ni}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/issue_valid_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/issue_ready_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/issue_req_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/issue_rsp_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/rsp_valid_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/rsp_ready_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/rsp_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/fpu_rnd_mode_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/fpu_fmt_mode_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/spatz_req_valid_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/spatz_req_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_req_ready_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_rsp_valid_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_rsp_ready_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_rsp_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vlsu_req_ready_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vlsu_rsp_valid_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vlsu_rsp_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vsldu_req_ready_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vsldu_rsp_valid_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vsldu_rsp_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/sb_enable_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/sb_wrote_result_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/sb_enable_o}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/sb_id_i}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/spatz_req}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/spatz_req_valid}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/spatz_req_illegal}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vstart_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vstart_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vl_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vl_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vtype_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vtype_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/decoder_req}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/decoder_req_valid}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/decoder_rsp}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/decoder_rsp_valid}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/buffer_spatz_req}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/req_buffer_ready}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/req_buffer_valid}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/req_buffer_pop}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/read_table_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/read_table_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/write_table_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/write_table_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/scoreboard_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/scoreboard_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/wrote_result_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/wrote_result_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/narrow_wide_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/narrow_wide_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/wrote_result_narrowing_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/wrote_result_narrowing_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/retire_csr}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/stall}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_stall}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vlsu_stall}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vsldu_stall}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/running_insn_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/running_insn_q}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/next_insn_id}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/running_insn_full}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_rsp}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_rsp_valid}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/vfu_rsp_ready}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/rsp_valid_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/rsp_ready_d}
add wave -noupdate -group i_controller {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_controller/rsp_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/clk_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rst_ni}
add wave -noupdate -group i_vlsu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_req_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_req_valid_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_req_ready_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vlsu_rsp_valid_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vlsu_rsp_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_waddr_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_wdata_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_we_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_wbe_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_wvalid_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_id_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_raddr_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_re_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_rdata_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_rvalid_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_req_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_req_valid_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_req_ready_i}
add wave -noupdate -group i_vlsu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_rsp_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_rsp_valid_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_finished_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_str_finished_o}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_req_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_spatz_req_valid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_is_strided}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_is_indexed}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/state_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/state_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/store_count_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/store_count_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_wdata}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_wid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_push}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_rvalid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_rdata}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_pop}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_rid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_req_id}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_id}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_full}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/rob_empty}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_operation_valid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_operation_last}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_counter_max}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_counter_en}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_counter_load}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_counter_delta}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_counter_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_counter_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_port_finished_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_idx_counter_delta}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_idx_counter_q}
add wave -noupdate -group i_vlsu -expand -subitemconfig {{/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_spatz_req.id} {-color {Medium Orchid} -height 16}} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_spatz_req}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_spatz_req_ready}
add wave -noupdate -group i_vlsu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vlsu_rsp_o}
add wave -noupdate -group i_vlsu -color Orchid {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vlsu_rsp_valid_o}
add wave -noupdate -group i_vlsu -expand -subitemconfig {{/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_insn_pending_q[1]} {-color Orchid -height 16}} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_insn_pending_q}
add wave -noupdate -group i_vlsu -expand -subitemconfig {{/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_insn_pending_d[1]} {-color Orchid -height 16}} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_insn_pending_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_empty}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_finished_o}
add wave -noupdate -group i_vlsu -color Orchid {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_valid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_finished_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_finished_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_insn_finished_q}
add wave -noupdate -group i_vlsu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_insn_finished_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/clk_i}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_pop}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_push}
add wave -noupdate -group i_vlsu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_d}
add wave -noupdate -group i_vlsu -color Orchid -expand -subitemconfig {{/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.id} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.vd} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.vsew} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.vl} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.vstart} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.rs1} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.is_load} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.is_strided} {-color Orchid -height 16} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q.is_indexed} {-color Orchid -height 16}} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_insn_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_idx_counter_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_counter_max}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_counter_en}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_counter_load}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_counter_delta}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_counter_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_counter_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_addr}
add wave -noupdate -group i_vlsu -color {Medium Orchid} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vd_vreg_addr}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vs2_vreg_addr}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vd_elem_id}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vs2_elem_id_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vs2_elem_id_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/pending_index}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_addr_offset}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/busy_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/busy_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vlsu_finished_req}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_req}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_req_valid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/spatz_mem_req_ready}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_operation_valid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_operation_last}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_is_load}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_is_vstart_zero}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_is_addr_unaligned}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_is_single_element_operation}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_single_element_size}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_idx_single_element_size}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_is_addr_unaligned}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_is_single_element_operation}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/commit_single_element_size}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vreg_addr_offset}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/offset_queue_full}
add wave -noupdate -group i_vlsu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_req_d}
add wave -noupdate -group i_vlsu -expand -subitemconfig {{/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_req_q.rsp_valid} {-color {Medium Orchid} -height 16}} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_req_q}
add wave -noupdate -group i_vlsu -color {Medium Orchid} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_req_valid_q}
add wave -noupdate -group i_vlsu -color {Medium Orchid} {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_req_ready_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_req_valid_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vrf_req_ready_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/vreg_start_0}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/catchup}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_id}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_data}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_svalid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_strb}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_lvalid}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_req_last}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_pending_d}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_pending_q}
add wave -noupdate -group i_vlsu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/mem_pending}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/clk_i}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/rst_ni}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/flush_i}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/testmode_i}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/full_o}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/empty_o}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/usage_o}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/data_i}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/push_i}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/data_o}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/pop_i}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/gate_clock}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/read_pointer_n}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/read_pointer_q}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/write_pointer_n}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/write_pointer_q}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/status_cnt_n}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/status_cnt_q}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/mem_n}
add wave -noupdate -group fifo {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vlsu/i_fifo_commit_insn/mem_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/clk_i}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/rst_ni}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/hart_id_i}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/spatz_req_i}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/spatz_req_valid_i}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/spatz_req_ready_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vfu_rsp_valid_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vfu_rsp_ready_i}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vfu_rsp_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_waddr_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_wdata_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_we_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_wbe_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_wvalid_i}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_id_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_raddr_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_re_o}
add wave -noupdate -group i_vfu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_rdata_i}
add wave -noupdate -group i_vfu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_rvalid_i}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/fpu_status_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_psout_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_sout_o}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_res_out_o}
add wave -noupdate -group i_vfu -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/spatz_req}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/spatz_req_valid}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/spatz_req_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_state_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_state_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_feature_load_count}
add wave -noupdate -group i_vfu -color Orchid {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_kernel_load_count}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_compute_counter}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_result_counter}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_loading_active}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/macvv_instruction_active}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vl_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vl_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/start_counter}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/busy_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/busy_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/nr_elem_word}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/state_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/state_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/ipu_result_tag}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/fpu_result_tag}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_result_tag}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/result_tag}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/input_tag}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vstart}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/stall}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_operand_ready_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_operand_ready_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/op1_is_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/op2_is_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/op3_is_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/operands_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/valid_operations}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/pending_results}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/word_issued}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/running_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/running_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/is_fpu_insn}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/is_dimc_insn}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/is_fpu_busy}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/is_ipu_busy}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/is_dimc_busy}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/scalar_result}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/last_request}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_state_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_state_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_done}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/current_element_idx}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_element_sel}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/compute_pulse}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_loop_mode}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/result_counter}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/comp_active}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_loop_active}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_buffer}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_buffer_psin}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_buffer_psin_2}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/buffer_idx}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/psin_buffer_idx}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/psin_chunk_idx}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/psin_write}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/burst_write}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vrf_chunk_idx}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_result_wide}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/fifo_head_is_loop}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/narrowing_upper_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/narrowing_upper_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/widening_upper_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/widening_upper_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/result}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/result_valid}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/result_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/ipu_result}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/ipu_result_valid}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/ipu_in_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/fpu_result}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/fpu_result_valid}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/fpu_in_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_result}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_result_valid}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_in_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/operand1}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/operand2}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/operand3}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/in_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_pointer_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_pointer_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/reduction_operand_request}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vreg_wbe}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vreg_we}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vreg_r_req}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vreg_addr_q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vreg_addr_d}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/vreg_wdata}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_vreg_wdata}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_write_active}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_in_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_operand1}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_operand2}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_operand3}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_result}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_result_tag}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_result_valid}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_result_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/int_ipu_busy}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/ipu_wide_operand1}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/ipu_wide_operand2}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/ipu_wide_operand3}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_ready}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_result_4bit}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_psout}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_COMPE}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_FCSN}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_MODE}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_FA}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_FD}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_ADDIN}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_Q}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_D}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_RA}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_WA}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_RCSN}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_RCSN0}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_RCSN1}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_RCSN2}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_RCSN3}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_WCSN}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_WEN}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_M}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_MCT}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_select_F}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/_select_K}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_32bit_result}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_fifo_head}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_fifo_tail}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/dimc_fifo_count}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/base_addr}
add wave -noupdate -group i_vfu {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vfu/chunk_offset}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/clk_i}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/rst_ni}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/testmode_i}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/waddr_i}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/wdata_i}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/we_i}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/wbe_i}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/wvalid_o}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/raddr_i}
add wave -noupdate -expand -group i_vrf -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/re_i}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/rdata_o}
add wave -noupdate -expand -group i_vrf -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/rvalid_o}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/waddr}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/wdata}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/we}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/wbe}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/raddr}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/rdata}
add wave -noupdate -expand -group i_vrf {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/write_request}
add wave -noupdate -expand -group i_vrf -expand {/tb_bin/i_dut/i_cluster_wrapper/i_cluster/gen_core[0]/i_spatz_cc/i_spatz/i_vrf/read_request}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 4} {8962000 ps} 1} {{Cursor 5} {8962000 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 210
configure wave -valuecolwidth 513
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {8960336 ps} {8963664 ps}
